export const ProjectsData = [
	{
		id: 1,
		title: 'Food-order website',
		about: `Front and Back end integrated website for ordering food`,
		tags: [
			'React.js',
			'React router',
			'React Bootstrap',
			'Firebase',
			'Express.js',
			'MongoDB',
		],
		demo: 'https://food-order-context-api.web.app/',
		github: 'https://github.com/Mokaddis-ALIF/food-order-context-api-client',
		image: 'https://i.ibb.co/pXtyQHt/Food-order.png',
	},
	{
		id: 2,
		title: 'Watch shop website',
		about: `Front and Back end integrated website for buying watches`,
		tags: [
			'React.js',
			'React router',
			'Swiper',
			'Firebase',
			'Express.js',
			'MongoDB',
		],
		demo: 'https://rolex-watch-52190.web.app/',
		github: 'https://github.com/Mokaddis-ALIF/watch-shop-context-api-frontend',
		image: 'https://i.ibb.co/tsDpPjM/watch-shop-website.png',
	},
	{
		id: 3,
		title: 'Book store website',
		about: `Front and Back end integrated website for buying books`,
		tags: [
			'React.js',
			'React router',
			'Swiper',
			'Firebase',
			'Express.js',
			'MongoDB',
		],
		demo: 'https://book-shop-context-api.web.app/',
		github: 'https://github.com/Mokaddis-ALIF/book-store-client-context-api',
		image: 'https://i.ibb.co/LkC1fWw/book-store-website.png',
	},
	{
		id: 4,
		title: 'Airbnb Clone',
		about: 'Mainly a frontend website as airbnb clone',
		tags: ['React.js', 'React router', 'MUI', 'Netlify'],
		demo: 'https://startling-empanada-f56ef1.netlify.app/',
		github: 'https://github.com/Mokaddis-ALIF/airbnb-clone',
		image: 'https://i.ibb.co/1fp23Xm/airbnb.png',
	},
	{
		id: 5,
		title: 'Adventure and tour website',
		about: 'Mainly a frontend website for adventurous and tour seeking people',
		tags: ['JavaScript', 'Swiper', 'SCSS'],
		demo: 'https://adventure-and-tour.netlify.app/',
		github: 'https://github.com/Mokaddis-ALIF/Adventure-tour-website',
		image: 'https://i.ibb.co/QnYT1Nx/tour.png',
	},
];
